// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdsulovxrpxogfaeiahx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdkc3Vsb3Z4cnB4b2dmYWVpYWh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjk5NjUsImV4cCI6MjA3MDg0NTk2NX0.mCy71hAK3UNu4ra_0hKArs97kza_-2eshu-TCsJig5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});